/*
Create a list for scores less than 50
Create a list for scores greater than 80

Get the lowest score from low scores, get the index

*/

List<Integer> scores = new List<Integer>{65, 45, 80, 90, 45, 40, 95, 30};

scores.add(20);
System.debug(scores); 

List<Integer> lowScores = new List <Integer>();
List<Integer> highScores = new List <Integer>(); 

for(Integer eachScore : scores) {
if( eachScore < 50 ){
    lowScores.add(eachScore);
}else{
    
}



}
    
    
